# config file version
apiVersion: 1

# list of datasources to insert/update
# available in the database
datasources:
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: db.:5432
    database: mandeebot_db #changed db from text to mlflow db
    user: mandeebot
    secureJsonData:
      password: pass #changed password from 12345 to pass
    jsonData:
      sslmode: 'disable'